---
download_url: "http://wordpress.org/latest.tar.gz"
wpdirectory: "/var/www/wordpress/"
wp_cli:
  url:
    "https://raw.githubusercontent.com/wp-cli/\
    builds/gh-pages/phar/wp-cli.phar"
  title: "'Igor Skorokhodov'"
  admin: "igor"
  admin_email: "test@email.com"
  admin_password: "wordpress"
